version: "3.8"
services:
  postgres_db:
    image: postgres:latest
    container_name: POSTGRES
    environment:
      - POSTGRES_USER:postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"